services:

  postgres:
    image: postgres:alpine3.18
    container_name: pg_db_test_3
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - posgresql3:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pg_db_test
    networks:
      - sb-postgres-network

  pgadmin4:
    image: dpage/pgadmin4:7.4
    container_name: pgadmin4_3
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pass
    depends_on:
      - postgres
    networks:
      - sb-postgres-network

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: unless-stopped
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pg_db_test
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: pass
#    depends_on:
#      - postgres
#    networks:
#      - sb-postgres-network

volumes:
  posgresql3:

networks:
  sb-postgres-network:
    driver: bridge